version: '3'
services:
  windows:
    image: ntno/ubuntu-build-base:1.0.0
    restart: "no"    
    volumes:
      - ${AWS_HOME_FOR_DOCKER}:/root/.aws:ro     #ro for read only
      - ${CURR_DIR_FOR_DOCKER}:/usr/src
    environment: 
      AWS_HOME_FOR_DOCKER: "${AWS_HOME_FOR_DOCKER}"
      CURR_DIR_FOR_DOCKER: "${CURR_DIR_FOR_DOCKER}"
      AWS_PROFILE: default
      AWS_SHARED_CREDENTIALS_FILE: /root/.aws/credentials
      AWS_SDK_LOAD_CONFIG: 1
      GITHUB_PERSONAL_USERNAME: "${GITHUB_PERSONAL_USERNAME}"
      GITHUB_PERSONAL_TOKEN: "${GITHUB_PERSONAL_TOKEN}"      